### ISSUE TITLE
[Edits] HTML: Output of examples

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#737] opened 2022-05-05 20:47 UTC
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Many entries in the HTML section do not have the output of the example.

## List of entries with no output of the example

[`<video>`](https://www.codecademy.com/resources/docs/html/tags/video)
[`<strong>`](https://www.codecademy.com/resources/docs/html/tags/strong)
[`<q>`](https://www.codecademy.com/resources/docs/html/tags/q)
[`<picture>`](https://www.codecademy.com/resources/docs/html/tags/picture)
[h1-h6](https://www.codecademy.com/resources/docs/html/tags/h1-h6)
[`<form>`](https://www.codecademy.com/resources/docs/html/tags/form)
[`<em>`](https://www.codecademy.com/resources/docs/html/tags/em)
[`<cite>`](https://www.codecademy.com/resources/docs/html/tags/cite)
[`<button>`](https://www.codecademy.com/resources/docs/html/tags/button)
[`<br>`](https://www.codecademy.com/resources/docs/html/tags/br)
[`<blockquote>`](https://www.codecademy.com/resources/docs/html/tags/blockquote)
[`<audio>`](https://www.codecademy.com/resources/docs/html/tags/audio)
[`<a>`](https://www.codecademy.com/resources/docs/html/tags/a)
[`<details>`](https://www.codecademy.com/resources/docs/html/semantic-html/details)
[`<summary>`](https://www.codecademy.com/resources/docs/html/semantic-html/summary)

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by ethan-master-coding** [comment] 2022-05-05 20:48
(We need the typo label removed. irrelevant to this issue)

**Comment by Dusch4593** [comment] 2022-05-05 22:20
@ethan-master-coding Hey there! Do we have one or two examples of which entries are missing output?

**Comment by ethan-master-coding** [comment] 2022-05-05 22:36
@Dusch4593 There are 10+ I believe. I will edit the OP when I  can get on my computer and have the list.

**Comment by ethan-master-coding** [comment] 2022-05-06 00:04
@Dusch4593 cant edit the OP right ow but here is an image of all the entries I found before

![image](https://user-images.githubusercontent.com/92686703/167045874-fee741bc-6e56-44ca-b936-9f10af099d34.png)

And can you look at #653

**Comment by Dusch4593** [comment] 2022-05-06 17:25
> cant edit the OP right now but here is an image of all the entries I found before

Did you want to take issue on and draft a PR? If so, I can assign you. For each example output, let's screen-shot an image (size < 1MB), save in a file, and add the file to the `media/` directory.

**Comment by ethan-master-coding** [comment] 2022-05-06 17:44
@Dusch4593 as of right now no I will see if anybody else wants to do it first.

**Comment by ethan-master-coding** [comment] 2022-05-07 18:48
@Dusch4593 edited the OP. I changed my mind and I will take on this issue. I won't do the header, since the problem with the screenshot not showing the true size of them and audio and video tags since a screenshot won't work well.

**Comment by Dusch4593** [comment] 2022-05-09 20:41
@ethan-master-coding No problem! 👍🏻 

A couple things before going forward with the PR for this issue:

- I highly recommend utilizing [Codecademy Workspaces](https://www.codecademy.com/pages/workspaces) for these changes because you can easily copy/paste the example HTML into the workspace editor to immediately render a result, which can then be captured in an image to be included underneath of the entry's example snippet.

> I won't do the header, since the problem with the screenshot not showing the true size of them and audio and video tags since a screenshot won't work well.  

- Just to be clear, the issue is not with screenshots but with the way that GH-flavored HTML is rendered on the Codecademy Docs site. For now this is an issue that we can't immediately address in the contribution, so I recommend we actually stick with using screenshots of the rendered markup instead (see [Markdown headings](https://github.com/Codecademy/docs/blob/main/content/markdown/concepts/headings/headings.md?plain=1#L38)).

- For future issues, let's let either myself or one of my colleagues (from Codecademy) check off the "Issue is assigned" checkbox after the issue has been assigned to you. Checks like this (and the one for labels) are supposed to be handled by maintainers, anyway.

**Comment by ethan-master-coding** [comment] 2022-05-09 21:22
@Dusch4593 

Ok. What about the video and audio tags. (For the image tag I am just going to attach the image)

**Comment by ethan-master-coding** [comment] 2022-05-13 20:01
@Dusch4593 before I start working on this can you tell me how to do the audio tag. I cant just attach the video and image so the only thing I need to know now is the audio tag.

**Comment by Dusch4593** [comment] 2022-05-17 19:34
@ethan-master-coding Firstly, let's hold off on any edits to `tags/tersm/a/a.md` (in HTML Tags: `<a>`) because I'm currently working on that one for another PR.

> And how many PRs are a manageable amount for you and the other maintainers? (I have a list of HTML tags that are not currently in the docs so I am going to making entries for them)

For now, submit only one for this issue and work on no more than 10 entries, new and/or existing (we can allow for this many since the edits are expected to be so few).

> I cant just attach the video and image so the only thing I need to know now is the audio tag. And can you get a video about CC so I can use it for the video tag?

Can you explain this one to me, again? Are we trying to find out how to render actual audio/video output with a CC-related link?

**Comment by ethan-master-coding** [comment] 2022-05-17 19:39
@Dusch4593 I think the example for the video tag would look best if we had a video instead of a screenshot of a video. And for the audio tag would be better to have an actual audio tag since you (as the user) interacts with it.

**Comment by Dusch4593** [comment] 2022-05-17 19:43
@ethan-master-coding While I agree it would be better, I'm not entirely certain embedding `<video>` and `<audio>` tags in [GH-markdown](https://github.github.com/gfm/) is possible. Screenshots (or maybe gifs) would be the best option but sound/user interaction would not be possible.

**Comment by ethan-master-coding** [comment] 2022-05-17 19:49
@Dusch4593 Ok. But you can embed videos with GH MD.

**Comment by Dusch4593** [comment] 2022-05-17 19:51
What's the syntax for it? I've never used it before.

**Comment by ethan-master-coding** [comment] 2022-05-17 19:52
`![alt text if video does not load | video](file path)` I think

**Comment by ethan-master-coding** [comment] 2022-05-17 19:58
@Dusch4593 just tested this and it looks like you just need the raw path 
![image](https://user-images.githubusercontent.com/92686703/168899229-b2b36331-1806-40c0-9351-ebf6335277d6.png)
![image](https://user-images.githubusercontent.com/92686703/168899327-4ae8b13e-df9c-4a48-887b-8dcebd70f688.png)

**Comment by Dusch4593** [comment] 2022-05-17 20:01
> @Dusch4593 just tested this and it looks like you just need the raw path

Yeah but it seems like you have to download the file first before it can be added to the file. I just tried this too and was able to embed a video:

https://user-images.githubusercontent.com/23144845/168898898-fca79752-7abf-48ed-a373-37a31d67491d.mp4

Let me check with my team on this one real quick because I noticed that the video I got was 6.1 MB (from a <1 minute video) and I just want to confirm whether size would be an issue.

**Comment by ethan-master-coding** [comment] 2022-05-17 20:07
@Dusch4593 GH does not support audio files so I will just use a gif

**Comment by Dusch4593** [comment] 2022-05-17 20:11
> @Dusch4593 GH does not support audio files so I will just use a gif

That's what I thought. Hopefully they'll implement it in the future somehow.

**Comment by ethan-master-coding** [comment] 2022-05-17 20:11
> > @Dusch4593 GH does not support audio files so I will just use a gif
> 
> That's what I thought. Hopefully they'll implement it in the future somehow.

Yea. unless I am overlooking an audio format https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by Dusch4593** [comment] 2022-05-17 20:14
Nope, not seeing any audio formats in there.

**Comment by ethan-master-coding** [comment] 2022-05-17 20:18
@Dusch4593 I found something and we may be able to embed audio. Let me test it.

**Comment by Dusch4593** [comment] 2022-05-17 20:21
After I tried to drag/drop an **.mp3** file:

<img width="833" alt="Screen Shot 2022-05-17 at 4 21 05 PM" src="https://user-images.githubusercontent.com/23144845/168903075-c330a41a-c0f4-4968-84d9-f8a554ce3b8e.png">

**Comment by ethan-master-coding** [comment] 2022-05-17 20:22
@Dusch4593 I tried doing this:
`![test](./Cartoon (Sting) - Twin Musicom.mp3)` Just a random audio file from the YT audio librery

**Comment by Dusch4593** [comment] 2022-05-17 20:23
Did it work?

**Comment by ethan-master-coding** [comment] 2022-05-17 20:24
Nope. Unfortently. It was formated as plain text

**Closed** 2022-06-02 17:47 UTC
Labels: enhancement, html
