### ISSUE TITLE
[Bug/Error] Leaderboard last updated time

### ISSUE THREAD

**Issue by ethan-master-coding** [Codecademy/docs#755] opened 2022-05-17 17:42 UTC
### Actual Behavior

It should display the last the leaderboard was updated.

### Expected Behavior

Display a random time from a few minutes ago to a few hours ago.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

**Comment by Dusch4593** [comment] 2022-06-15 13:12
@ethan-master-coding Can you expand on what you mean? I just checked the leaderboard and there seems to be a state for the last time it was updated:

<img width="1122" alt="Screen Shot 2022-06-15 at 9 10 48 AM" src="https://user-images.githubusercontent.com/23144845/173835418-c1b9d4c8-c46e-4ab6-be79-dcb5f122f456.png">

cc: @christian-dinh

**Comment by ethan-master-coding** [comment] 2022-06-15 14:44
@Dusch4593 It may take a few refreshes for that to change. But when was the last commit/merge? About 22 hours ago not 31 min ago (or and a half hours when I am right this)

**Comment by christian-dinh** [comment] 2022-07-11 19:50
I'm able to reproduce the issue, I've filed a bug for the engineering team to look at when we have a chance but I'm not sure when that'll be. Thanks for bringing this to our attention!

**Comment by Dusch4593** [comment] 2022-07-18 14:14
Closing this for now since @christian-dinh filed with the engineering team.

**Closed by Dusch4593** 2022-07-18 14:14 UTC
Labels: bug
