### ISSUE TITLE
[Edit] Python: Errors

### ISSUE THREAD

**Issue by Dusch4593** [Codecademy/docs#856] opened 2022-07-26 13:32 UTC
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Please add information about the `TypeError` to [the existing entry](https://www.codecademy.com/resources/docs/python/errors) (under the "Exception" section). Include 1-3 descriptive sentences and one (1) code snippet example.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

**Comment by sharkipelago** [comment] 2022-07-27 02:30
Hi I'm new to contributing to open source, but think I could handle this task. Could I  be assigned to this issue?

**Comment by KTom101** [comment] 2022-08-05 18:06
@sharkipelago I will assign you this! You can take a look at our Contribution Guide [here](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md). Also, feel free to send us questions on this thread if you have any.

**Comment by sharkipelago** [comment] 2022-08-05 21:48
@KTom101 thank you! Also I think the issue is assigned task is still not checked off? Is there something I need to do in order to check it?

**Comment by KTom101** [comment] 2022-08-05 21:50
@sharkipelago I've just checked it off. Thank you for that!

**Comment by sharkipelago** [comment] 2022-08-07 18:58
@KTom101  hi! I've submitted a PR, but I think the Value Error information is wrong. For the Value Error the example is correct but I think the description describes a Type Error . So I used that description and created a new example for the Type error information. Should I submit a new issue or PR to fix the Value Error description?

**Comment by KTom101** [comment] 2022-08-07 20:19
@sharkipelago Thanks for pointing this out! You can edit the "Value Error" description in the same PR you just submitted.

**Comment by sharkipelago** [comment] 2022-08-07 21:53
@KTom101 I updated the PR is there anything else I need to do or just wait for feedback when it gets reviewed?

**Comment by KTom101** [comment] 2022-08-07 23:37
@sharkipelago All you have to do is wait for feedback now. There are usually 2-3 rounds of review before merging.

**Comment by SSwiniarski** [comment] 2022-10-30 13:52
This was addressed with PR [875](https://github.com/Codecademy/docs/pull/875)

**Closed by SSwiniarski** 2022-10-30 13:52 UTC
Labels: enhancement, python
