### ISSUE TITLE
[Edit] JavaScript this

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5067] opened 2024-08-19 18:09 UTC
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `this` concept entry under JavaScript. The entry lives in `content/javascript/concepts/this/this.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a `Codebyte Example` section that provides a codebyte example demonstrating the concept in use
2) Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by davialano** [comment] 2024-08-20 00:11
Can I collaborate in this Issue?

**Comment by aSagCoder** [comment] 2024-08-20 07:37
Hi, I'd love to contribute to this!

**Comment by mamtawardhani** [comment] 2024-08-20 07:46
Hey @davialano You’re assigned 🎉 In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions before approval.

Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by mamtawardhani** [comment] 2024-08-20 07:47
Hey @aSagCoder since @davialano commented first, the issue is assigned to them. You can look through the available [issues](https://github.com/Codecademy/docs/issues) and let me know if anything interests you.

**Comment by Hajar-El-Mhassani** [comment] 2024-08-30 09:23
I would like to contribute on this

**Comment by mamtawardhani** [comment] 2024-08-30 10:31
> I would like to contribute on this

Hey @Hajar-El-Mhassani the other author is already working on this. You can check the other avaiable issues and comment on the  one that interests you 😃

**Comment by davialano** [comment] 2024-09-23 11:26
Can somebody close this issue?

**Comment by mamtawardhani** [comment] 2024-09-23 11:28
> Can somebody close this issue please?

Apologies, I guess it wasn't linked to the issue else it would have closed automatically.

**Closed** 2024-09-23 11:27 UTC
Labels: enhancement, good first issue, javascript, claimed
