### ISSUE TITLE
[Edit] HTML Add Media: id

### ISSUE THREAD

**Issue by christian-dinh** [Codecademy/docs#3290] opened 2023-09-18 21:20 UTC
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the HTML Attributes entry. The entry lives in docs/content/html/concepts/attributes/terms/id.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by TadasRuzga** [comment] 2023-09-19 11:58
Hi, can I be assigned to this?

**Comment by TadasRuzga** [comment] 2023-09-19 13:49
Hi, can I be assigned to this

**Comment by TadasRuzga** [comment] 2023-09-19 15:34
Hi, can I be assigned to this.

**Comment by SSwiniarski** [comment] 2023-09-19 16:46
@TadasRuzga You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by Fsbalami** [comment] 2023-09-21 10:18
@christian-dinh am interested in this issue

**Comment by SSwiniarski** [comment] 2023-09-21 11:24
@Fsbalami You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

If this is your first time contributing, can you let us know how you came across this repo?

**Comment by SSwiniarski** [comment] 2023-10-09 16:35
@Fsbalami It's been over two weeks, are you still working on this issue. Note that in another week it will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment] 2023-10-15 19:48
@Fsbalami This issue has been unassigned due to inactivity.

**Comment by ashstockman** [comment] 2023-10-17 13:14
@christian-dinh I am interested in taking this issue on, I found out about Docs through Codecademy's GitHub course.

**Comment by SSwiniarski** [comment] 2023-10-17 16:17
@ashstockman You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by VaishnaviMudaliar** [comment] 2023-10-28 13:08
Hey is this issue still open? Can i work on it?

**Comment by SSwiniarski** [comment] 2023-10-28 14:39
@VaishnaviMudaliar since @ashstockman removed themselves, you're assigned.

**Comment by VaishnaviMudaliar** [comment] 2023-10-29 06:43
Thank you for assigning it to me! :)

**Comment by SSwiniarski** [comment] 2023-11-09 17:41
@VaishnaviMudaliar It's been two weeks. Are you still working on this issue? Note that in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment] 2023-11-15 17:35
@VaishnaviMudaliar  this is being unassigned due to inactivity.

**Comment by ROOHITH** [comment] 2023-11-17 13:02
@SSwiniarski I would like to work on this.
do i need to change everything which was previously written and make it simple ?.

**Comment by SSwiniarski** [comment] 2023-11-17 16:35
@ROOHITH The issue is not asking you to rewrite anything. Just to add an illustrative image.

**Comment by SSwiniarski** [comment] 2023-11-17 16:36
@ROOHITH You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by ROOHITH** [comment] 2023-11-21 13:17
this is happening while i try to install corepack enable
Internal Error: EPERM: operation not permitted, open 'G:\installation files\node exe\pnpm.cmd'
Error: EPERM: operation not permitted, open 'G:\installation files\node exe\pnpm.cmd'

**Comment by SSwiniarski** [comment] 2023-11-22 16:46
@ROOHITH since I see a PR, I presume you resolved your issue?

**Comment by ROOHITH** [comment] 2023-11-24 01:50
when will be the changes updated on the doc, this is my first open-source contribution.

**Closed** 2023-11-24 14:33 UTC
Labels: enhancement, good first issue, html, claimed
