### ISSUE TITLE
[Term Entry] Python:NumPy built-in-functions Matrix Multiplication

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#4477] opened 2024-03-19 16:40 UTC
### Reason/inspiration (optional)

"We would like a new term entry on the `built-in-functions` term for [Numpy](https://www.codecademy.com/resources/docs/numpy): matrix multiplication. The entry should go in a new file under `docs/content/numpy/concepts/built-in-functions/terms/dot/dot.md`.

The entry should describe the term and how it is used within statistical analysis. Also include: 
- An "Example" section that explains readers how to use the dot function to do matrix multiplication.
- Should contain informations for functions and syntax.
- Should have a python codebyte with working code snippet showcasing this function.
Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue."

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by deenovita** [comment] 2024-03-22 01:16
Hello, may I work on this issue? Thank you!

**Comment by letsbuildanything** [comment] 2024-03-22 02:54
@deenovita  You’re assigned :tada:  In addition to the documents linked in the description, please also look at the [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide).  After creating a PR, the maintainer(s) (with the collaborator label) will add comments/suggestions to address any revisions prior to approval.
Is this your first contribution to Codecademy Docs? If so, we’re curious to know how you found out about contributing to Docs.

**Comment by letsbuildanything** [comment] 2024-04-06 14:29
@deenovita It's been two weeks. Are you still working on this entry? Note that in another week it will be unassigned due to inactivity.

**Comment by amal-george-8895** [comment] 2024-04-06 14:33
Hi,
I think there is a mistake. I havent been assigned any issues.
Im still waiting for a issuse to be assigned to me.

Thank you.

**Comment by nateginn** [comment] 2024-04-16 20:02
@letsbuildanything Hello, may I complete this project? Attempting to complete my Git/GitHub training. I have taken python courses from CodeAcademy, prior to this course. Contributing to the Docs Repo is the only step I have left to complete. thank you.

**Comment by letsbuildanything** [comment] 2024-04-17 03:51
@nateginn You're assigned!🎉

**Comment by nateginn** [comment] 2024-04-17 06:39
@letsbuildanything Is there a way to message you directly through GitHub?

**Comment by letsbuildanything** [comment] 2024-04-17 07:20
@nateginn, if you read the description closely, you'll see it already addresses your question. Just follow the instructions to create a file for the `dot` function. Feel free to ask any additional questions here(if it's only related to this issue) or in the Discussions forum—no need to message me directly on GitHub.

**Comment by nateginn** [comment] 2024-05-06 06:53
@letsbuildanything  I have created a new folder dot and new file dot.md I added content by researching multiple sites and then rewriting the content in my own words. I checked the example code in my IDE and confirmed it worked. There is one place where I quoted information I copied from numpy.org but I sourced the quote. I was not sure how to rewrite it more clearly. This is my first PR. I used the template and created the dot.md file in vscode, not on github. I am eager to learn, please provide me with helpful feedback.

**Closed** 2024-05-10 04:36 UTC
Labels: good first issue, new entry, numpy, claimed
