### ISSUE TITLE
[Term Entry] NumPy Built-in-function: .sort()

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#5700] opened 2024-11-27 08:04 UTC
### Reason/inspiration (optional)

We would like a new term entry on the `.sort()` math method in NumPy. The entry should go in a new file under `content/numpy/concepts/built-in-functions/terms/sort/sort.md`.       
  
The entry should include:      
  
- An introduction to the concept      
- A `Syntax` section that provides the syntax for the concept     
- An `Example` section that provides an example demonstrating the concept in use    
 - A `Codebyte Example` section that provides an example demonstrating this term
 
Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

**Comment by SimhadriMadhubabu** [comment] 2024-11-28 05:36
Hi, I’d like to work on this issue. Could you please assign it to me?

**Comment by Maverick073** [comment] 2024-12-01 18:01
Hi ! If the issue is still open , i would be happy to work on this issue .

**Comment by mamtawardhani** [comment] 2024-12-02 05:46
Hey @Maverick073, for future reference, please raise a PR only after an issue has been assigned to you. As I can see @SimhadriMadhubabu is working on this issue, so we might have to close your PR.

Quick confirmation here: @SimhadriMadhubabu are you still working on this issue?

**Comment by Maverick073** [comment] 2024-12-02 06:43
Hi @mamtawardhani ! I apologise and in future I will raise the pr after it's been assigned to me . As I couldn't see any pr being raised or other activity , I decided to raise the pr . Thank you !

**Comment by mamtawardhani** [comment] 2024-12-09 08:13
Hey @Maverick073 you can raise a PR for this issue on a new branch, as the current author is inactive, I'm assigning this to you. Let me know if that is okay. 😃

**Comment by Maverick073** [comment] 2024-12-09 18:29
Sure , I am very much happy to take this issue and work upon. I will raise the pr once the issue is completed . Thank You !

**Closed** 2024-12-19 15:45 UTC
Labels: good first issue, new entry, numpy, claimed
