### ISSUE TITLE
[Edit] HTML Add Media: Links

### ISSUE THREAD

**Issue by codecademy-docs** [Codecademy/docs#3231] opened 2023-09-11 15:11 UTC
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML Links. The entry should go in the existing file in docs/content/html/concepts/links/links.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by maxx-l** [comment] 2023-09-12 09:16
Hi, I would like to work on this issue 
Cheers

**Comment by maxx-l** [comment] 2023-09-12 09:50
I would like to be assigned please

**Comment by KTom101** [comment] 2023-09-13 00:20
@maxx-l You're assigned 🎉 In addition to the documents linked in the description, please also take a look at our [Contribution Guide](https://www.codecademy.com/resources/docs/contribution-guide). After creating a PR, the maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approval.

Is this your first contribution to Codecademy Docs? If so, we're curious to know how you found out about contributing to Docs.

**Comment by maxx-l** [comment] 2023-09-14 06:50
Thank @KTom101 , yes it's my first contribution. It's the Git/Github course that brought me here

**Comment by SSwiniarski** [comment] 2023-10-21 12:57
@maxx-l I unassigned you because you closed your PR.

**Comment by KNBahir** [comment] 2023-10-21 13:59
@codecademy-docs I wanted to taking this issue on, kindly let me to.

**Comment by Kosyenka** [comment] 2023-10-21 15:38
@codecademy-docs  I'm also interested to take on this issue.

**Comment by DakuwoN** [comment] 2023-10-22 03:41
I am interested as well, if available...

**Comment by SSwiniarski** [comment] 2023-10-22 13:25
@KNBahir You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by SSwiniarski** [comment] 2023-10-22 13:26
@Kosyenka, @DakuwoN, @KNBahir claimed this one first.

**Comment by SSwiniarski** [comment] 2023-11-04 14:56
@KNBahir It's been two weeks. Are you still working on this issue? Note in another week this will be unassigned due to inactivity.

**Comment by SSwiniarski** [comment] 2023-11-12 16:42
@KNBahir this is being unassigned due to inactivity.

**Comment by DakuwoN** [comment] 2023-11-12 17:15
@SSwiniarski I am willing to tackle this issue 🙏

**Comment by SSwiniarski** [comment] 2023-11-13 12:30
@DakuwoN, You're assigned.

**Comment by DakuwoN** [comment] 2023-11-21 02:23
I am not exactly sure what needs done here?

**Comment by SSwiniarski** [comment] 2023-11-21 12:25
@DakuwoN The issue is to create an image that illustrates part of the existing entry and add it to the entry.

**Comment by SSwiniarski** [comment] 2023-11-26 17:51
@DakuwoN It's been two weeks. Are you still working on this entry. Note in another week this will be unassigned due to inactivity.

**Comment by DakuwoN** [comment] 2023-11-28 03:44
Sorry I took a break for Thanksgiving. I will resume and finish tomorrow

**Comment by DakuwoN** [comment] 2023-11-29 02:00
I am sorry, I got tied up with school, you can un assign me as I won't have time this week.

**Comment by nsLittle** [comment] 2023-11-29 15:34
I would like to claim this issue as my first contribution.  I am attempting this as part of the GIt/GitHub lesson on Codecademy.  Many thanks.

**Comment by SSwiniarski** [comment] 2023-11-29 20:25
@nsLittle You're assigned! You can check out the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/CONTRIBUTING.md) for additional information on contributing.
See [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) for an overview of styling tips that the [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) covers in detail.
After creating a PR, maintainer(s) (with the collaborator label) will add in comments/suggestions to address any revisions prior to approving.
	
In addition, please head over to the [Docs Forum](https://discuss.codecademy.com/c/community/community-docs/2205) if you have any questions about Docs or reply to the thread on [Possible Content Discussion](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868) to share ideas and collaborate with other contributors, maintainers, or super users to determine good future issues that will help expand Docs!

**Comment by F-Viedge** [comment] 2024-01-24 20:46
Hi I'd like to claim this issue as part of the GitHub course, thank you in advance.

**Comment by SSwiniarski** [comment] 2024-01-25 12:08
@F-Viedge This issue is already assigned and has a PR open for it.

**Comment by F-Viedge** [comment] 2024-01-25 12:12
@SSwiniarski Okay thanks for getting back to me I'll try find another...

**Comment by F-Viedge** [comment] 2024-01-26 14:18
Hi I'm still in the woods for a  issue to work on as part of the course could you please notify me when this becomes available?

**Comment by nsLittle** [comment] 2024-01-27 11:23
@F-Viedge <https://github.com/F-Viedge>, here is what I did:
1. Go to Codecademy's "claim an issue" link
<https://www.codecademy.com/resources/docs/contribution-guide/claiming-an-issue>
.
2. Go to GitHub "doc repository" link
<https://github.com/Codecademy/docs/issues> part way down the page on #1.
3. Go to the "issues" tab <https://github.com/Codecademy/docs/issues> (as
mentioned on the page in link #1).
4. See image #1 below.  Notice the colored tags on each line item. Look for
issues with the purple "good first issue."  Now make sure the issue does
NOT have a red "claimed" tag.  Many of the issues applicable to us newbies
are already claimed, but they are there!
5. See image #2 below.  Notice the first and third line. It has the purple
"good first issue" and NO "claimed" tag.  You can claim either of those
tags if they pique your interest.  Otherwise, there should be more pickings
down the line.


@SSwiniarski <https://github.com/SSwiniarski>, I am having issues with (a)
inserting an image into a Markdown document (the problem i have is an issue
related to the path i have to the image), and (b) I am not sufficiently
learn-ed in git commands, and I need to stop panicking and go through
the  whole process again.  Is there someone who can help me check the
path?  I've Google'd, ChaptGPT'd, but I really need a human to ensure I
have the path correct.  Thank you!


[image: iamge1.png]

[image: image2.png]

**Comment by SSwiniarski** [comment] 2024-01-27 13:07
@nsLittle Instructions on how to add an image in an entry are in the style guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting).

The path will be to the Docs repository media folder.

**Comment by SSwiniarski** [comment] 2024-01-28 13:01
@nsLittle you closed your PR, does that mean you're no longer working on this issue?

**Comment by nsLittle** [comment] 2024-01-28 13:37
No, oops.  I thought I asked for a pull request for you to look at my
update.  *sigh* big apologies.  Can I still have the issue?

**Comment by SSwiniarski** [comment] 2024-01-29 12:39
@nsLittle go ahead and make another PR.

**Comment by F-Viedge** [comment] 2024-01-30 07:12
@nsLittle sorry for the late reply thanks for guidance on finding issues, I feel I'm getting a bit sidetracked from the codecademy course I'm  busy with and don't yet have enough knowledge to tackle the current issues available...I still think this one is something I could add to.

When you're done with it if you guys could let me have a go at it I'd really appreciate it. Thank you @SSwiniarski

**Comment by nsLittle** [comment] 2024-02-01 16:40
> @nsLittle it's ok. The new PR just wasn't linked to the issue so I didn't see it.

I see that you "linked a pull request" with the green "open" button.  Does that mean you fixed my PR snafu, and the issues is waiting for someone to check the new updates?  Or is there still an action item on my plate?  Please advise.  Thank you for your continued help and patience in this matter.

**Comment by SSwiniarski** [comment] 2024-02-01 16:44
@nsLittle Nothing on your end, just wait for reviews by maintainers on your PR and respond to their edits.

**Comment by ParkerSwift** [comment] 2024-02-12 15:16
Can I be assigned?

**Comment by F-Viedge** [comment] 2024-02-15 15:02
Hi can I please contribute to this?

**Comment by ishg-153** [comment] 2024-03-15 14:24
@nsLittle This issue is unassigned due to lack of response on the PR.

**Comment by kimikatiti** [comment] 2024-03-15 16:15
May I please tackle this issue?

**Comment by ishg-153** [comment] 2024-03-15 18:39
@kimikatiti You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry.

**Comment by Dan-Tyas** [comment] 2024-04-03 19:29
Is thre any chance i can be assigned to this issue please?

**Comment by ishg-153** [comment] 2024-05-15 07:11
Hey @kimikatiti! There has been no PR created for this Issue. If you don't respond with status on the entry or a PR, this issue will be unassigned from you.

**Comment by ishg-153** [comment] 2024-05-15 07:12
@Dan-Tyas if @kimikatiti doesn't respond and you are still willing to take on this issue, you will be assigned.

**Comment by htnweb** [comment] 2024-05-15 08:23
Hi @ishg-153 I would like to work on this issue as part of my learn git and github course. It would be my first contribution. Thanks

**Comment by ishg-153** [comment] 2024-05-17 14:10
@htnweb You're assigned!🎉 You can look through the [Contribution Guide](https://github.com/Codecademy/docs/blob/main/.github/CONTRIBUTING.md) to know more about contributing to Codecademy Docs. Check out the [Content Standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [Style Guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md), they’ll help you with creating your entry. 

I see this is your first time contributing to Codecademy Docs. How did you find out about us?

**Comment by ismailkatilo** [comment] 2024-05-25 20:15
@ishg-153 I'd like to work on this issue, Could you assign it to me please?

**Comment by ismailkatilo** [comment] 2024-05-26 05:54
@ishg-153 Could you assign this issue to me please?

**Comment by ismailkatilo** [comment] 2024-05-26 09:47
@SSwiniarski  Could you assign this issue to me please?

**Comment by ismailkatilo** [comment] 2024-05-27 07:44
@ishg-153 I'd like to work on this issue, Could you assign it to me please?

**Comment by ismailkatilo** [comment] 2024-05-27 11:19
@ishg-153

**Comment by ishg-153** [comment] 2024-05-27 11:37
@ismailkatilo This issue is already assigned and has an active PR. Please checkout [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+-label%3A%22claimed%22) and ask to be assigned to one that interests you.

**Comment by shukriarahimitech** [comment] 2024-05-28 11:20
@maxx-l am interested in this issue.

**Comment by Atilanb** [comment] 2024-07-10 06:44
@ishg-153 Can I be assigned please?

**Comment by ishg-153** [comment] 2024-07-11 09:40
Hey @maxx-l and @Atilanb, This issue is already assigned to @htnweb. Please checkout [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+-label%3A%22claimed%22) and ask to be assigned to one that interests you.

**Closed** 2024-08-14 15:46 UTC
Labels: enhancement, good first issue, html, claimed
