### ISSUE TITLE
[Edit] JavaScript Arrays: `.reduce()`

### ISSUE THREAD

**Issue by pinalpithadiya** [Codecademy/docs#620] opened 2022-03-14 19:08 UTC
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

The [reduce](https://www.codecademy.com/resources/docs/javascript/arrays/reduce) method of array works weirdly on  complex structure i.e. reducing array of objects.
please add an example for the complex structure to it.

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

**Comment by ddwildin** [comment] 2022-05-01 02:08
Would adding a simple example of reduce with an array of objects be enough or should an explanation be provided?

**Comment by KTom101** [comment] 2022-05-08 03:00
@ddwildin A brief explanation with the example should be provided. May I assign you to this?

**Comment by pinalpithadiya** [comment] 2022-05-09 12:13
I am sorry for the delayed response, yes, you can work on it, there are simple examples already, you need to add the explanation to whatever you are adding there.

**Comment by Dusch4593** [comment] 2022-07-18 14:19
Hey @ddwildin 👋🏻  this is Brandon from the Codecademy Free Team. I just wanted to check in and ask how you were doing and see if you had any questions about making a PR for this issue?

**Comment by cesscode** [comment] 2022-08-22 18:50
Hello, I am interested in working on this issue. Can I add a .reduce() method example with a brief description of how it works?

**Comment by Dusch4593** [comment] 2022-08-22 19:50
@cesscode You're assigned! To answer your question, my recommendation would be to edit the existing "Codebyte Example" section and replace the current codebyte snippet with a more complex use-case of `.reduce()` (i.e., reducing an array of objects).

**Comment by cesscode** [comment] 2022-08-22 22:37
Hello, I can't seem to find the "Codebyte Example". I took the Codecademy open source course, and I want to make my first contribution, I will love you to help me out maybe

**Comment by Dusch4593** [comment] 2022-08-22 22:50
@cesscode The "Codebyte Example" can be found towards the bottom of the JS arrays `.reduce()` entry here: https://www.codecademy.com/resources/docs/javascript/arrays/reduce

**Comment by Dusch4593** [comment] 2022-09-16 22:30
Hey @cesscode how are you? Just wanted to check in and see how everything has been with writing the content for this issue? Anything I can do to help?

**Comment by itsvipindev** [comment] 2022-10-03 04:36
Hello @Dusch4593  can i try this i have good understanding of how javascript works

**Comment by Dusch4593** [comment] 2022-10-03 16:56
Hey @itsvipindev! This issue is presently assigned to someone. Feel free to continue working on the PRs for the issues you're currently assigned to. 😄

**Comment by SSwiniarski** [comment] 2022-10-30 13:34
Hey @cesscode, since there've been several weeks without activity, I'm going to unassign you so someone else can work on this. Please feel free to sign up for another issue when you have time.

@imvipindev, are you still interested in this issue?

**Comment by oliviap103** [comment] 2022-10-31 15:58
Hi, I would like to work on this issue as part of the Codecademy Learn Git & GitHub course.

**Comment by SSwiniarski** [comment] 2022-10-31 16:19
@oliviap103, I've assigned you. Thanks for contributing.

**Comment by fjorwb** [comment] 2022-11-02 15:47
May I be assigned to this I think that I could make a contribution for this issue. Thanks.

**Comment by SSwiniarski** [comment] 2022-11-02 16:31
@fjorwb, the issue is already assigned to @oliviap103. If you want to contribute, there are still plenty of unassigned issues.

**Comment by fjorwb** [comment] 2022-11-02 16:55
Thank you for your prompt response. Anyways, please let me know if it could not be accomplished.

**Comment by Diogolisbon** [comment] 2022-11-06 11:29
Hello, can I be assigned? Thanks

**Closed** 2022-11-25 19:08 UTC
Labels: enhancement, good first issue, javascript, typo, claimed
